name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.2
      
    - name: Build the Docker image
      run: docker build -t "${{ secrets.DOCKER_REPO }}" .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Push Docker image to Docker Hub
      run: docker push "${{ secrets.DOCKER_REPO }}"
